name: ci-dev

on:
  pull_request:
    branches:
      - develop

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate HTML Files
        run: |
          test -f index.html
          test -f lahore.html
          test -f hunza.html
          test -f karachi.html
          test -f swat.html